### ISSUE TITLE
[Build] Issue with libpng 

### ISSUE THREAD

**Issue by shinra-electric** [shinra-electric/Arm-Build-Script-for-RPCS3#11]
This is a follow-up to #10.

Building fails at `cellPngDec.cpp`. 

CMake is using an older version of `libpng` despite the `-DUSE_LOCAL_LIBPNG` flag set to off.

[printfcmd.txt](https://github.com/user-attachments/files/16921161/printfcmd.txt)

I cannot reproduce this locally.

**Comment by Ghostkwebb** [comment]
is there anything else I could do? Cause I don't know where things are going wrong

**Comment by shinra-electric** [comment]
> is there anything else I could do? Cause I don't know where things are going wrong

I'm not sure why it's going wrong either, since I can't reproduce the issue myself. I don't really have much time to look into it further right now, but I'll take another look when I can. I might ask you to try a few things if I get some ideas.

In the meantime there are a few things you can try: 

- Use something like [VirtualBuddy](https://github.com/insidegui/VirtualBuddy) to try the script in a VM. This would be a clean macOS install, so might not have the same issue. 
- If you have any friends with Macs, maybe ask if they can try it. 
- Wait for me to finish setting up GitHub Actions. I'm planning on posting pre-compiled releases.

**Comment by Ghostkwebb** [comment]
Using virtual buddy,

OS : 14.6.1

Commands Ran Before executing script:-
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" and added to path
brew install cmake
brew install ninja

AND IT WOKED WTF

So now I nedd to figure out what went wrong with mine
Thanks for this amazing script btw

**Comment by shinra-electric** [comment]
I spotted a problem with the script that was likely messing up the cmake configuration.

Could you try it again the same as last time where you uncomment libpng on line `127` and change `-DUSE_SYSTEM_LIBPNG` to `OFF`?

**Comment by Ghostkwebb** [comment]
> I spotted a problem with the script that was likely messing up the cmake configuration.
> 
> Could you try it again the same as last time where you uncomment libpng on line `127` and change `-DUSE_SYSTEM_LIBPNG` to `OFF`?

After cloning and rerunning the script, the build was successful and the application was built. THANKS!

Terminal output for reference : 
[reference.txt](https://github.com/user-attachments/files/16958082/reference.txt)
