### ISSUE TITLE
AppleClang used instead of intended Clang from brew

### ISSUE THREAD

**Issue by archanox** [shinra-electric/Arm-Build-Script-for-RPCS3#12]
During the build I get
```
-- The C compiler identification is AppleClang 16.0.0.16000026
-- The CXX compiler identification is AppleClang 16.0.0.16000026
```

which causes build issues later on.

**Comment by shinra-electric** [comment]
The script uses Apple clang from the Xcode command line tools, so this isn’t a valid issue. 

If you are getting errors later, post the terminal output here and I’ll have a look (in a .txt file)

**Comment by archanox** [comment]
Oh, I just assumed we should be using the brew llvm as it's something we're pulling in. I'll close this issue if it's working as intended.

I'll replicate the issue I'm having when I have a chance. I looked at the main repo and found the issue was caused by an old version of llvm and I assumed it was also due to using Apple Clang here.

**Comment by shinra-electric** [comment]
LLVM isn’t used to compile the app, it’s used by RPCS3 to compile the PPU and SPU modules.

Technically we should be building LLVM from the 3rd-party submodules, but it’s much easier and faster to bundle in Homebrew’s pre-compiled library. 

Anyway, I’ll close this. If you have another issue you can make a new one.
