### ISSUE TITLE
[Build] Including SDL to the script

### ISSUE THREAD

**Issue by meh7an** [shinra-electric/Arm-Build-Script-for-RPCS3#8]
Currently the SDL controller handler is not compiled alongside this script. It will be so helpful to include that as well, maybe by an optional build parameter.

**Comment by shinra-electric** [comment]
I can add the CMake flags, so if someone wants to use SDL they can just toggle them on. 

I'll add it after I do a bit of testing, but it should work if you add the `USE_SDL` flag and set to `ON`.
If you want to use Homebrew SDL, add the `USE_SYSTEM_SDL` too. 

The purpose of the script is just for building locally, and I use pre-compiled Homebrew as much as possible to make compilation fast. In the future I plan on trying to get Github Actions to make a proper release with everything included.

**Comment by shinra-electric** [comment]
After testing, I found it didn't add much time to compilation, so I've just turned it on. 
it seems to be working ok.
